import Link from 'next/link';
import { Leaf, ShieldCheck, HeartHandshake, Sprout, BadgeCheck, Phone, Check, Activity } from 'lucide-react';
import { Process, Stories, Faqs, JourneyCTA, SectionTitle } from '@/components/sections';
import ConsultationForm from '@/components/consultation-form';
import PatientHero from '@/components/patient-hero';
import KneeExplorer from '@/components/knee-product-viewer';
const differences=[['Expert Practitioners','Our BAMS-qualified doctors combine deep Ayurvedic knowledge with years of clinical experience.',BadgeCheck],['Personalized Care','Every treatment plan is customized to your unique constitution and health needs.',HeartHandshake],['Holistic Focus','We address root causes rather than just symptoms for lasting results.',Sprout],['Traditional & Safe','Treatments use traditionally prepared Ayurvedic formulations with a focus on safety and individual suitability.',ShieldCheck],['Proven Results','Our track record of successful outcomes speaks for itself across various conditions.',Activity]] as const;
export default function Home(){return <main id="main"><PatientHero/><div className="trust-strip"><div className="container"><span><ShieldCheck/>BAMS certified Ayurvedic clinic</span><span><Sprout/>Natural, non-surgical care</span><span><HeartHandshake/>Personalized to your constitution</span></div></div>
<section className="section"><div className="container intro-grid"><div className="intro-photo"><img src="/assets/herbal-preparation.webp" alt="Traditional herbal oils and natural Ayurvedic ingredients" loading="lazy"/><div className="experience-stamp"><strong>12<span>+</span></strong><span>YEARS OF<br/>TRUSTED CARE</span></div></div><div className="intro-copy"><span className="eyebrow">WELCOME TO JIVAN URJA</span><h2>Pune’s trusted<br/><em>Ayurvedic healing center.</em></h2><p>At Jivan Urja, we blend ancient Ayurvedic wisdom with modern understanding to provide comprehensive care for your body, mind and spirit. Our 12+ years of experience in Pune have helped thousands regain their health naturally.</p><p>At our Chikitsalaya, our personalized approach addresses the root cause of your health concerns — delivering lasting relief through personalized Ayurvedic care.</p><Link href="/about-us" className="text-link">Discover our approach</Link><div className="intro-signature"><Leaf size={22}/><span>Authentic healing for body, mind & spirit</span></div></div></div></section>
<section id="services" className="section care-section"><div className="container"><SectionTitle eyebrow="CARE THAT GOES TO THE ROOT" title="Our holistic services" description="Comprehensive Ayurvedic solutions for complete well-being"/><div className="care-card"><KneeExplorer/><div className="care-copy"><span className="eyebrow">JIVAN URJA CHIKITSALAYA</span><h3>A natural approach<br/>to joint health.</h3><p>Our Ayurvedic clinic specializes in joint health, particularly knee comfort, using time-tested therapies tailored to your unique constitution. Non-surgical, natural, and effective.</p><h4>Conditions treated</h4><ul className="condition-list">{['Knee Discomfort','Ayurvedic Management of Knee Joint Health','Meniscus Discomfort','Ligament Discomfort'].map(t=><li key={t}><Check size={16}/>{t}</li>)}</ul><Link href="/request-consultation" className="button">Book consultation</Link></div></div></div></section>
<section className="section difference-section"><div className="container"><SectionTitle eyebrow="THOUGHTFUL CARE, EVERY STEP" title="The Jivan Urja difference" description="Why thousands choose us for their Ayurvedic healing journey"/><div className="difference-grid">{differences.map(([title,body,Icon])=><article key={title}><span className="feature-icon"><Icon size={25} strokeWidth={1.4}/></span><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
<section className="comfort-section"><div className="container comfort-grid"><div><span className="eyebrow">MOVE WITH GREATER EASE</span><h2>Natural knee<br/><em>comfort solutions.</em></h2><p>Our specialized Ayurvedic approach to knee health focuses on:</p><ul>{['Reducing discomfort and inflammation naturally','Strengthening joint tissues and muscles','Improving mobility and flexibility','Addressing the root cause of joint issues'].map(t=><li key={t}><Check size={18}/>{t}</li>)}</ul><Link href="/request-consultation" className="button button-light">Book your free consultation</Link></div><blockquote><span>“</span>Our knee treatments combine ancient Ayurvedic therapies with modern understanding to help you move with greater comfort and ease.<div className="quote-line"/><small>JIVAN URJA CHIKITSALAYA</small></blockquote></div></section>
<Process/><Stories/>
<section className="section team-section"><div className="container team-grid"><img src="/assets/jivanurjahospital.webp" alt="Jivan Urja Chikitsalaya clinic" loading="lazy"/><div><span className="eyebrow">MEET OUR EXPERT TEAM</span><h2>Our healing family.</h2><p>Qualified Ayurvedic practitioners dedicated to your well-being.</p><p>BAMS-qualified doctors and trained therapists working together for your health.</p><div className="credentials"><div><BadgeCheck/><strong>BAMS Qualified</strong><span>Bachelor of Ayurvedic Medicine</span></div><div><ShieldCheck/><strong>AYUSH Registered</strong><span>Ministry of Ayurveda, Yoga & Naturopathy</span></div></div><Link href="/about-us" className="text-link">Meet our practitioners</Link></div></div></section><Faqs/>
<section id="contactus" className="section booking-section"><div className="container booking-grid"><div><span className="eyebrow">LET’S TAKE THE FIRST STEP</span><h2>Book your<br/><em>free consultation.</em></h2><p>Our Ayurvedic experts will get back to you within 24 hours.</p><a className="booking-phone" href="tel:+918805777500"><Phone size={24}/>+91 8805777500</a><p className="clinical-note"><ShieldCheck size={22}/>Our clinical protocols are administered by BAMS-qualified physicians in accordance with standardized Ayurvedic practice guidelines.</p><Link className="text-link" href="/request-consultation">View consultation details</Link></div><ConsultationForm/></div></section><JourneyCTA/></main>}
